### ISSUE TITLE
Editing is not integrated with git

### ISSUE THREAD

**Issue by bricewge** [NicolasPetton/pass#8]
Unless pass this mode is not integrated with git. After modifying a password the changes should be saved in git too like pass.

**Comment by NicolasPetton** [comment]
`pass-insert` calls `password-store-insert`, which itself calls `pass insert`, so I'm not sure there is anything I can or should do about it.

**Comment by bricewge** [comment]
The git backend is used appropriately for adding or removing, however editing isn't integrated with pass. It seems to be coming from `password-store-edit`.

**Comment by danielsz** [comment]
@NicolasPetton Indeed, the problem is upstream, with `password-store.el`
Not sure how to notify the author, but opening a ticket seems our best bet.

**Comment by NicolasPetton** [comment]
@danielsz it's been a long time, and I forgot about this issue.
Have you since then contacted the author? Is the issue fixed upstream?

**Comment by bricewge** [comment]
I just posted about it on the [mailling list](https://lists.zx2c4.com/pipermail/password-store/2017-July/002983.html).

**Comment by svend** [comment]
password-store.el author here. I've created a branch that runs "pass edit" instead of editing the file directly in Emacs.

https://github.com/svend/password-store/tree/with-editor

I'll push the change upstream if there are no objections.

**Comment by svend** [comment]
I've released password-store.el 1.0.0 which adds git integration for password-store-edit.

**Comment by NicolasPetton** [comment]
Svend Sorensen <notifications@github.com> writes:

> I've released password-store.el 1.0.0 which adds git integration for
> password-store-edit.

Great, thank you!

**Comment by bricewge** [comment]
`password-store.el 1.0.1` is now available in MELPA, so the issue should be close.
However I still have issues with `password-store-insert`, I'll continue the conversation on the [mailling list](https://lists.zx2c4.com/pipermail/password-store/) of the appropriate package.
Thanks for your work @svend!

**Comment by danielsz** [comment]
Seems that editing an entry does not create a commit. I am experiencing the same issue as @firmart.

**Comment by benthamite** [comment]
Can someone clarify the status of this issue? In line with reports by @danielsz and @firmart, the command `edit` (`e`) fails to create a commit. In such cases, it seems that one must use the command line (`$ pass edit`).

**Comment by doolio** [comment]
> Can someone clarify the status of this issue?  ... the command edit (e) fails to create a commit.

I can confirm this is the case for me also.

**Comment by DamienCassou** [comment]
Can any of you create a new issue if you are still affected by this issue?

**Comment by doolio** [comment]
Apologies @DamienCassou , I think you got notified because I added a comment here yesterday and then deleted it. I can confirm this issue no longer exists.
